# Generated by Django 2.2.7 on 2019-12-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.DecimalField(decimal_places=13, default=None, max_digits=20)),
                ('Y', models.DecimalField(decimal_places=13, default=None, max_digits=20)),
                ('Unique_Squirrel_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('Hectare', models.CharField(default=None, max_length=3)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.CharField(default=None, max_length=20)),
                ('Hectare_Squirrel_Number', models.IntegerField(blank=True, default=0)),
                ('Age', models.CharField(blank=True, default=None, max_length=20)),
                ('Primary_Fur_Color', models.CharField(blank=True, default=None, max_length=15)),
                ('Highlight_Fur_Color', models.CharField(blank=True, default=None, max_length=20)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(blank=True, default=None, max_length=20)),
                ('Color_notes', models.CharField(blank=True, default=None, max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default=None, max_length=20)),
                ('Above_Ground_Sighter_Measurement', models.CharField(blank=True, default=None, max_length=10)),
                ('Specific_Location', models.CharField(blank=True, default=None, max_length=100)),
                ('Running', models.BooleanField(default=None)),
                ('Chasing', models.BooleanField(default=None)),
                ('Climbing', models.BooleanField(default=None)),
                ('Eating', models.BooleanField(default=None)),
                ('Foraging', models.BooleanField(default=None)),
                ('Other_Activities', models.CharField(blank=True, default=None, max_length=100)),
                ('Kuks', models.BooleanField(default=None)),
                ('Quaas', models.BooleanField(default=None)),
                ('Moans', models.BooleanField(default=None)),
                ('Tail_flags', models.BooleanField(default=None)),
                ('Tail_twitches', models.BooleanField(default=None)),
                ('Approaches', models.BooleanField(default=None)),
                ('Indifferent', models.BooleanField(default=None)),
                ('Runs_from', models.BooleanField(default=None)),
                ('Other_Interactions', models.CharField(blank=True, default=None, max_length=100)),
                ('Lat_Long', models.CharField(blank=True, default=None, max_length=100)),
                ('Zip_Codes', models.CharField(blank=True, default=None, max_length=100)),
                ('Community_Districts', models.IntegerField(blank=True, default=None)),
                ('Borough_Boundaries', models.IntegerField(blank=True, default=None)),
                ('City_Council_Districts', models.IntegerField(blank=True, default=None)),
                ('Police_Precincts', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
