# Generated by Django 2.2.7 on 2019-12-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Above_Ground_Sighter_Measurement',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Borough_Boundaries',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='City_Council_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Color_notes',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Combination_of_Primary_and_Highlight_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Community_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare_Squirrel_Number',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Lat_Long',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_Interactions',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Police_Precincts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Zip_Codes',
        ),
    ]
